import type { Metadata } from "next";
import { Geist_Mono, Montserrat, Patrick_Hand } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const seekuw = localFont({
  src: "./fonts/SEEKUW.otf",
  variable: "--font-heading",
  display: "swap",
});
import { ThemeProvider } from "@/components/theme-provider";
import { SiteBackground } from "@/components/site-background";
import { GraffitiCursor } from "@/components/cursor/graffiti-cursor";
import { DEFAULT_THEME, THEME_VALUES } from "@/lib/themes";

const montserrat = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const patrickHand = Patrick_Hand({
  variable: "--font-hand",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${montserrat.variable} ${patrickHand.variable} ${seekuw.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative min-h-full flex flex-col overflow-x-hidden">
        <SiteBackground />
        <ThemeProvider
          attribute="data-theme"
          defaultTheme={DEFAULT_THEME}
          themes={THEME_VALUES}
          enableSystem={false}
          disableTransitionOnChange
        >
          {children}
          <GraffitiCursor />
        </ThemeProvider>
      </body>
    </html>
  );
}
